### PR TITLE
Add bank-wise unit tests.

### PR DESCRIPTION
**Pull request by kannoth**
Update the unit tests for bank-wise components.

### CODE REVIEW

**Comment by kannoth** [comment]
@efzulian @myzinsky : Updated the unit tests for the Bankwise components. Kindly review and merge to tukl-msd.

**Comment by efzulian** [comment]
Dear Subash,
do you see errors when you execute make test?
Maybe you forgot to push something?

def test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_refresh(self):
uses refBCmdTrace = 'traces/REFB.commands.trace'
I could find this file:
./test/data/REFB.commands.trace

**Comment by efzulian** [comment]
Please double check all the tests you've created.
Maybe it is a good idea to assign the trace name to a variable and reuse the variable for tests with the same trace. E.g.:  my_favorite_varible_name = 'traces/data/PASR.commands.trace'
Then if you have to fix all the tests because you changed the path it will be easier.

**Comment by efzulian** [comment]
As we know, it is always a good idea execute all tests before opening the pull-request. Probably you forgot to push something.  As a suggestion you can run "git status" after pushing to see if you forgot some file changed locally.

**Comment by kannoth** [comment]
@efzulian  Thank you very much for your review. As there were many file, I pushed the _test.py_ with the wrong path. Anyway I pushed the correct file now. All the test must pass now.
Thanks.

**Comment by efzulian** [comment]
Hi Subash, you can see that your fork is "2 commits ahead, 10 commits behind tukl-msd:master. ".
It is important, specially now, that you merge all the changes from the tukl-msd/DRAMPower repository into your fork. As a rule it is always good to be in sync with the main repository (in your case tukl-msd/DRAMPower). The reason is that some changes may change the output. Thus, the reference files used for testing would be outdated.

You can find online how to keep your fork up to date. My suggestion is:

 List the remote repositories:
```
git remote -v
```
 Add tukl-msd as "upstream":
```
git remote add upstream https://github.com/tukl-msd/DRAMPower.git
```
 List the remote repositories again to see the difference:
```
git remote -v
```
Fetch the changes from "upstream"
```
git fetch upstream
```
 If you want to merge the changes from "upstream" to your master branch make sure you are in your master branch (could be any other branch):
```
git checkout master
```
Merge:
```
git merge upstream/master
```
In case of conflicts you have to solve them:
```
git mergetool
```
 Check the status (additionally you may have to add some file after solving conflicts):
```
git status
(git add <some file>)
```
Push the changes to your "origin":
```
git push origin HEAD
```
Check the web interface (github.com) you should not be behind the "upstream" repo anymore.

**Comment by efzulian** [comment]
I ran again the tests and some of them are failing, since I don't have much time to debug them for you, I will wait for your next commit. Maybe you will have to change the reference files after updating your repository anyway.

Ran 50 tests in 52.345s

FAILED (failures=4)
Makefile:141: recipe for target 'test' failed
make: *** [test] Error 1


Bank-wise drampower output for MICRON_1Gb_DDR3-1600_8bit_G_3s with the jpegencode transaction trace with Rho = 100% ... FAIL
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_25 (__main__.TestOutput)
Bank-wise drampower output for MICRON_1Gb_DDR3-1600_8bit_G_3s with the jpegencode transaction trace with Rho = 25% ... FAIL
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_50 (__main__.TestOutput)
Bank-wise drampower output for MICRON_1Gb_DDR3-1600_8bit_G_3s with the jpegencode transaction trace with Rho = 50% ... FAIL
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_75 (__main__.TestOutput)
Bank-wise drampower output for MICRON_1Gb_DDR3-1600_8bit_G_3s with the jpegencode transaction trace with Rho = 75% ... FAIL

**Comment by kannoth** [comment]
I have cloned a fresh repo with last commit. All the tests are PASSING. Please check it one more time.
`kannoth@kannoth:~/Documents/Private/HiWi/Wehn/myFork2$ make test
make: *** No rule to make target 'test'.  Stop.
kannoth@kannoth:~/Documents/Private/HiWi/Wehn/myFork2$ cd DRAMPower/
kannoth@kannoth:~/Documents/Private/HiWi/Wehn/myFork2/DRAMPower$ ls
ChangeLog  Makefile  memspecs  README.md  SConstruct  src  test
kannoth@kannoth:~/Documents/Private/HiWi/Wehn/myFork2/DRAMPower$ make test
wget --quiet --output-document=traces.zip https://github.com/Sv3n/DRAMPowerTraces/archive/master.zip
unzip traces.zip && mkdir -p traces && mv DRAMPowerTraces-master/traces/* traces/ && rm -rf DRAMPowerTraces-master
Archive:  traces.zip
e640d3f7ff3766cdf4a799943f81e6ffe0946fb4
   creating: DRAMPowerTraces-master/
   creating: DRAMPowerTraces-master/traces/
  inflating: DRAMPowerTraces-master/traces/LICENSE  
  inflating: DRAMPowerTraces-master/traces/commands.trace  
  inflating: DRAMPowerTraces-master/traces/mediabench-epic.trace  
  inflating: DRAMPowerTraces-master/traces/mediabench-h263encode.trace  
  inflating: DRAMPowerTraces-master/traces/mediabench-jpegencode.trace  
  inflating: DRAMPowerTraces-master/traces/mediabench-mpeg2encode.trace  
python test/test.py -v
test_make_wo_args_completes_returns_0 (__main__.TestBuild)
'make -j4' should return 0 ... ok
test_make_clean_removes_compiler_output (__main__.TestClean)
'make clean' should remove all .o and .a and .d files ... ok
test_libdrampower_output_matches_reference (__main__.TestLibDRAMPower) ... WARNING: All banks are already precharged!
Command: 9, Timestamp: 450, Bank: 0
WARNING: Bank is already active!
Command: 0, Timestamp: 550, Bank: 0
WARNING: Bank is already precharged!
Command: 3, Timestamp: 650, Bank: 0
ok
test_libdrampower_with_xerces_test_builds (__main__.TestLibDRAMPower)
libdrampower-based executable build should return 0 ... ok
test_libdrampower_without_xerces_test_builds (__main__.TestLibDRAMPower)
libdrampower-based executable build should return 0 ... ok
test_LPDDR2_1066_matches_reference (__main__.TestOutput)
drampower output for an LPDDR2-1066 trace matches reference ... ok
test_LPDDR2_1066_short_matches_reference (__main__.TestOutput)
drampower output for an LPDDR2-1066 trace matches reference ... ok
test_LPDDR2_1066_termination_matches_reference (__main__.TestOutput)
drampower output for an LPDDR2-1066 trace with termination power enabled matches reference ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_100_pasr_0 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 100% and PASR mode = 0 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_100_pasr_1 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 100% and PASR mode = 1 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_100_pasr_2 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 100% and PASR mode = 2 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_100_pasr_3 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 100% and PASR mode = 3 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_100_pasr_4 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 100% and PASR mode = 4 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_100_pasr_5 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 100% and PASR mode = 5 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_100_pasr_6 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 100% and PASR mode = 6 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_100_pasr_7 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 100% and PASR mode = 7 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_25_pasr_0 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 25% and PASR mode = 0 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_25_pasr_1 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 25% and PASR mode = 1 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_25_pasr_2 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 25% and PASR mode = 2 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_25_pasr_3 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 25% and PASR mode = 3 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_25_pasr_4 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 25% and PASR mode = 4 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_25_pasr_5 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 25% and PASR mode = 5 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_25_pasr_6 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 25% and PASR mode = 6 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_25_pasr_7 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 25% and PASR mode = 7 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_50_pasr_0 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 50% and PASR mode = 0 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_50_pasr_1 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 50% and PASR mode = 1 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_50_pasr_2 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 50% and PASR mode = 2 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_50_pasr_3 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 50% and PASR mode = 3 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_50_pasr_4 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 50% and PASR mode = 4 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_50_pasr_5 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 50% and PASR mode = 5 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_50_pasr_6 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 50% and PASR mode = 6 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_50_pasr_7 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 50% and PASR mode = 7 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_75_pasr_0 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 75% and PASR mode = 0 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_75_pasr_1 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 75% and PASR mode = 1 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_75_pasr_2 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 75% and PASR mode = 2 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_75_pasr_3 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 75% and PASR mode = 3 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_75_pasr_4 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 75% and PASR mode = 4 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_75_pasr_5 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 75% and PASR mode = 5 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_75_pasr_6 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 75% and PASR mode = 6 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_Sigma_75_pasr_7 (__main__.TestOutput)
Bank-wise drampower output for MICRONMICRON_1Gb_DDR3-1600_8bit_G with the PASR commands trace with Sigma = 75% and PASR mode = 7 ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_100 (__main__.TestOutput)
Bank-wise drampower output for MICRON_1Gb_DDR3-1600_8bit_G_3s with the jpegencode transaction trace with Rho = 100% ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_25 (__main__.TestOutput)
Bank-wise drampower output for MICRON_1Gb_DDR3-1600_8bit_G_3s with the jpegencode transaction trace with Rho = 25% ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_50 (__main__.TestOutput)
Bank-wise drampower output for MICRON_1Gb_DDR3-1600_8bit_G_3s with the jpegencode transaction trace with Rho = 50% ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_75 (__main__.TestOutput)
Bank-wise drampower output for MICRON_1Gb_DDR3-1600_8bit_G_3s with the jpegencode transaction trace with Rho = 75% ... ok
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_refresh (__main__.TestOutput)
drampower output for REFB trace matches reference ... ok
test_broken_trace (__main__.TestOutput)
running drampower with an invalid trace returns 0 ... ok
test_commands_trace_output_matches_reference (__main__.TestOutput)
drampower output for commands.trace example should be equal to test_commands_trace_output_matches_reference.out ... ok
test_no_arguments_error (__main__.TestOutput)
running drampower w/o arguments returns 1 ... ok
test_transaction_scheduler (__main__.TestOutput)
drampower output for LPDDR3-1333 with the jpegencode transaction trace matches reference ... ok
test_transaction_scheduler_with_self_refresh (__main__.TestOutput)
drampower output for LPDDR3-1333 with the jpegencode transaction trace matches reference ... ok

----------------------------------------------------------------------
Ran 50 tests in 123.982s

OK
`

**Comment by efzulian** [comment]
Please update your repository. Note this message:
"This branch is 2 commits ahead, 10 commits behind tukl-msd:master."

**Comment by kannoth** [comment]
Ok, now I got your point. I will do that. Thanks.

**Comment by efzulian** [comment]
Actually are two points:

1. update your repo because the results may change (this has to be done anyway).

2. even before the update I have 4 failures. Since you say that it works for you I will check again here (you can ignore for now since it works for you).

**Comment by efzulian** [comment]
The four tests that are failing here are:
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_100 (__main__.TestOutput) ... FAIL
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_25 (__main__.TestOutput) ... FAIL
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_50 (__main__.TestOutput) ... FAIL
test_MICRON_1Gb_DDR3_1600_8bit_G_3s_bankwise_Rho_75 (__main__.TestOutput) ... FAIL

The error is the same for all of them:

First differing element 126:
  WR Cmd Energy: 908549 pJ
  WR Cmd Energy: 908548 pJ

Note that the write cmd energy differs only in the last digit.
It seems to be related to rounding problems, maybe because of different compiler versions.

**Comment by kannoth** [comment]
I will do the first point. Second, I am sure it might be some little problem with your repo. It should not fail with last commit.

**Comment by kannoth** [comment]
Perhaps, not sure. Yeah compiler might be rounding .
This is the version I used.
kannoth@kannoth:~/Documents/DRAMPower$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2

**Comment by efzulian** [comment]
I'm using gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010.
Suggestion: test also with clang in your system.

**Comment by kannoth** [comment]
I think there is a serious rounding issue with gcc versions. Almost all the tests are failing for the official repository in the DRAM server with gcc 4.8

libdrampower-based executable build should return 0 ... ok
libdrampower-based executable build should return 0 ... ok
drampower output for an LPDDR2-1066 trace matches reference ... ERROR
drampower output for an LPDDR2-1066 trace matches reference ... ERROR
drampower output for an LPDDR2-1066 trace with termination power enabled matches reference ... ERROR
running drampower with an invalid trace returns 0 ... ok
drampower output for commands.trace example should be equal to test_commands_trace_output_matches_reference.out ... ERROR
running drampower w/o arguments returns 1 ... ok
drampower output for LPDDR3-1333 with the jpegencode transaction trace matches reference ... ERROR
drampower output for LPDDR3-1333 with the jpegencode transaction trace matches reference ... ERROR

**Comment by efzulian** [comment]
You can make tests more verbose and investigate what is going on.
You can use "self.maxDiff = None  # Show full diff on error." in test.py.

**Comment by efzulian** [comment]
The problem with the server is the python version. You can change the Makefile, target "test" to use "python2.7" instead of "python". It works (official DRAMPower repo).

**Comment by efzulian** [comment]
In the readme of DRAMPower "gcc - v4.4.3" is announced as a required package. I've been using other versions since always. :)

**Comment by efzulian** [comment]
Suggestion: update your repository. The sooner you do it the less conflicts you get.

**Comment by myzinsky** [comment]
Could you also have a look on the comments of Andreas here:
http://reviews.gem5.org/r/3525/

Maybe these things could also be fixed (maybe in a separated PR)

**Comment by kannoth** [comment]
@efzulian : I did the merge. Fortunately I did not have to change the test references for bank wise parameters. The clang were stopping for array indexing with singed integers.  This was fixed in a commit before the merge.
Compiled with _g++  4.9.2_ and _clang++ 3.5.0_ . There is not warnings and all tests are passing.

But in the DRAM server the _clang++ 3.4.2 _ fails with the below error.
`clang++ -O -W -pedantic-errors -Wextra -Werror -Wformat -Wformat-nonliteral -Wpointer-arith -Wcast-align -Wconversion -Wall -Werror -g   -std=c++0x -MMD -MF src/TraceParser.d -iquote src -o src/TraceParser.o -c src/TraceParser.cc
In file included from src/TraceParser.cc:37:
In file included from src/TraceParser.h:41:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/vector:65:
/usr/bin/../lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:340:13: error: rvalue reference to type 'vector<[2 * ...]>' cannot
      bind to lvalue of type 'vector<[2 * ...]>'
        this->swap(__x); `

Looks like some version incompatibility with STL. Not sure what is the issue, I have to look into that. No issues with _g++ 4.8.2_

**Comment by efzulian** [comment]
The CI system is ok for Linux. This is really good!

Nevertheless, it's failing for mac. Something related to the std library and "ioto()":

'make' should return 0 ... src/MemBankWiseParams.cc:76:25: error: no member named 'iota' in namespace 'std'
 std::iota(activeBanks.begin(), activeBanks.end(), 0);

Matthias, any idea?

**Comment by efzulian** [comment]
The build is working fine for Linux (according to the CI system).

There are some points we have to keep in mind:

1. Double check the build for mac. (Matthias?)

2. Find out why our code fails for some specific versions of compilers. (can be also problem with a version of a library as suggested by Subash).

Further improvements can be done in separate pull-requests.
I will merge this pull-request.

**Comment by efzulian** [comment]
Note:
the bug for mac was fixed with the inclusion of a header file (Thanh's suggestion via e-mail)

**Pull request merged**
